mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from django.conf.urls.static import static
from . import views
from django.conf import settings

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:user_id>/user_msg/', views.user_msg, name='user_msg'),
    path('<int:user_id>/user_msg_change/', views.user_msg_change, name='user_msg_change'),
    path('user_msg_create/', views.user_msg_create, name='user_msg_create'),
    path('user_msg_add/', views.user_msg_add, name='user_msg_add'),
    path('upload/', views.uploadImg),
    path('show/', views.showImg),
]

polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

class User_Register(models.Model):
    name=models.CharField(max_length=50)
    email = models.CharField(max_length=50,null=True,blank=True)
    payment = models.CharField(max_length=50)



class IMG(models.Model):
    img = models.ImageField(upload_to='img')

    name = models.CharField(max_length=20)
    GENDER_CHOICES = (
        (u'M', u'Male'),
        (u'F', u'Female'),
    )
    gender = models.CharField(max_length=2, choices=GENDER_CHOICES,default='M')

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Question, Choice, User_Register,IMG
from django.template import loader
from django.http import Http404
from django.shortcuts import get_object_or_404, render


def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    return render(request, 'polls/detail.html', {'question': question})


def user_msg(request, user_id):
    # 已有的msg
    user_msg = get_object_or_404(User_Register, pk=user_id)
    return render(request, 'polls/user_msg.html', {'user_msg': user_msg})

def user_msg_create(request):

    return render(request, 'polls/add_user.html', {'user_msg': user_msg})

def user_msg_add(request):
    # 已有的msg
    # user_msg = get_object_or_404(User_Register, pk=user_id)
    name = request.POST['name']
    email = request.POST['email']
    payment = request.POST['payment']
    user_msg=User_Register(name=name,email=email,payment=payment)
    user_msg.save()
    return HttpResponse("You're add succeed %s." % name)

def user_msg_change(request, user_id):

    user_msg = get_object_or_404(User_Register, pk=user_id)
    name = request.POST['name']
    email = request.POST['email']
    payment = request.POST['payment']

    user_msg.name=name
    user_msg.email=email
    user_msg.payment=payment
    user_msg.save()

    return HttpResponse("You're change succeed %s." % name)

def uploadImg(request):
    if request.method == 'POST':
        new_img = IMG(
            img=request.FILES.get('img'),
            name = request.FILES.get('img').name,
            gender=request.POST['gender']
        )
        sss= request.FILES.get('img')
        ppp=sss.size
        new_img.save()
    return render(request, 'polls/uploadimg.html')

def showImg(request):
    imgs = IMG.objects.all()
    content = {
        'imgs':imgs,
    }
    for i in imgs:
        print(i.img.url)
    return render(request, 'polls/showimg.html', content)

templates/polls/add_user.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>add user</h1>





    <form action="{% url 'polls:user_msg_add'  %}" method="post">

        <input type="text" name="name"  />
        <input type="text" name="email"  />
        <input type="text" name="payment"  />
        <br>
        <input type="submit" value="user_msg" />
    </form>


</body>
</html>

templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>


    <h1>{{ question.question_text }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
    {% endfor %}
    <input type="submit" value="Vote3" />
    </form>

</body>
</html>

templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    {% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

</body>
</html>

templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
</body>
</html>

templates/polls/showimg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% for img in imgs %}
<img src="{{ img.img.url }}" />
{% endfor %}

</body>
</html>

templates/polls/uploadimg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <form method="POST" enctype="multipart/form-data">

        <input type="file" name="img">
        <button type="submit">上传</button>

        <select name="gender">
            <option value="M">Male</option>
            <option value="F">Female</option>
        </select>


    </form>
</body>
</html>

templates/polls/user_msg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>{{ user_msg.name }}</h1>

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}




    <form action="{% url 'polls:user_msg_change' user_msg.id %}" method="post">

        <input type="text" name="name" value="{{ user_msg.name }}" />
        <input type="text" name="email" value="{{ user_msg.email }}" />
        <input type="text" name="payment" value="{{ user_msg.payment }}" />
        <br>
        <input type="submit" value="user_msg" />
    </form>


</body>
</html>